version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/day4-build-design-modernization/sample-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
